name: Playwright_Java_Tutorial

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      #Récupération du code
      - name: Checkout repository
        uses: actions/checkout@v4

      #Installation de Java (JDK 21 recommandé — 24 n'est pas encore full supporté)
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      #Installation des dépendances + compilation
      - name: Build project (skip tests)
        run: mvn clean install -DskipTests --no-transfer-progress

      #Installation Xvfb (support GUI headless)
      - name: Install xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      #Installation Playwright Browsers
      - name: Install Playwright browsers
        run: mvn playwright:install

      # Lancer les tests Java + Playwright en mode graphique virtuel
      - name: Run Playwright tests
        run: mvn test

      # Upload test reports on failure
      - name: Upload ExtentReports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: extent-reports
          path: target/extent-reports/

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
           ${{ runner.os }}-maven-

